# Generated by Django 5.1.7 on 2025-03-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField(unique=True)),
                ('server_name', models.CharField(max_length=255)),
                ('wipe_time', models.DateTimeField()),
                ('max_group', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
