# Generated by Django 5.1.7 on 2025-03-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_id', models.IntegerField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=255)),
                ('max_group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servers',
            },
        ),
        migrations.CreateModel(
            name='WipeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=10)),
                ('wipe_hour', models.CharField(max_length=10)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wipe_schedules', to='servers.server')),
            ],
            options={
                'db_table': 'wipe_schedules',
                'unique_together': {('server', 'day_name', 'wipe_hour')},
            },
        ),
    ]
