# Generated by Django 5.1.7 on 2025-03-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='server',
            table='servers',
        ),
    ]
