# Generated by Django 5.1.7 on 2025-03-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_server_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='id',
        ),
        migrations.AlterField(
            model_name='server',
            name='server_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
